Controllers/PengembalianController.cs
using ClosedXML.Excel;
using System.Diagnostics;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Mime;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using Xceed.Words.NET;
using Pnbp.Models;
using Pnbp.Entities;
using Xceed.Document.NET;
using NPOI.HSSF.Record;
using Oracle.ManagedDataAccess.Client;
using NPOI.OpenXmlFormats.Spreadsheet;
using Microsoft.Ajax.Utilities;
using System.Web.Http.Results;
using NPOI.Util;
using DocumentFormat.OpenXml.Wordprocessing;
using NPOI.SS.Formula.Functions;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.EMMA;

namespace Pnbp.Controllers
{
    [AccessDeniedAuthorize]
    public class PengembalianController : Controller
    {
        Models.PengembalianModel pengembalianmodel = new Models.PengembalianModel();

        public JsonResult GetListKantor()
        {
            List<Entities.ListKantor> result = pengembalianmodel.GetListKantor();

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetListBank()
        {
            List<Entities.ListBank> result = pengembalianmodel.GetListBank();

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GenerateSuratKeteranganPengembalian(string nomorsurat, string nomorberkas, string NamaProsedur, string namapemohon, string SetoranPnbp, string JumlahBayar)
        {

            if (!String.IsNullOrEmpty(nomorsurat) && nomorsurat.ToLower() == "undefined") nomorsurat = "";
            if (!String.IsNullOrEmpty(nomorberkas) && nomorberkas.ToLower() == "undefined") nomorberkas = "";
            if (!String.IsNullOrEmpty(NamaProsedur) && NamaProsedur.ToLower() == "undefined") NamaProsedur = "";
            if (!String.IsNullOrEmpty(namapemohon) && namapemohon.ToLower() == "undefined") namapemohon = "";
            if (!String.IsNullOrEmpty(SetoranPnbp) && SetoranPnbp.ToLower() == "undefined") SetoranPnbp = "";
            if (!String.IsNullOrEmpty(JumlahBayar) && JumlahBayar.ToLower() == "undefined") JumlahBayar = "";


            DateTime dateTime = DateTime.UtcNow.Date;
            using (MemoryStream ms = new MemoryStream())
            {
                string filename = Path.Combine(Server.MapPath(@"~/Format/"), "surat_keterangan.docx");
                DocX doc = DocX.Load(filename);

                doc.ReplaceText("{NOMOR_SURAT}", nomorsurat);
                doc.ReplaceText("{NOMOR_BERKAS}", nomorberkas);
                doc.ReplaceText("{NAMA_PROSEDUR}", NamaProsedur);
                doc.ReplaceText("{NAMA_PEMOHON}", namapemohon);
                doc.ReplaceText("{JUMLAH_SETOR}", SetoranPnbp);
                doc.ReplaceText("{JUMLAH_KELUAR}", JumlahBayar);

                doc.SaveAs(ms);

                Response.ContentType = "application/msword";
                Response.AddHeader("content-disposition", "inline; filename=" + "SuratKeterangan.docx");
                Response.AddHeader("content-length", ms.Length.ToString());
                Response.BinaryWrite(ms.ToArray());
                Response.End();
            }
            return View();
        }

        public ActionResult GenerateSuratKeteranganPengeluaran(string nomorsurat, string nomorberkas, string NamaProsedur, string namapemohon, string SetoranPnbp, string JumlahBayar, string atasNama)
        {

            DateTime dateTime = DateTime.UtcNow.Date;
            using (MemoryStream ms = new MemoryStream())
            {
                string filename = Path.Combine(Server.MapPath(@"~/Format/pengembalian"), "surat-keterangan-pengeluaran.docx");
                DocX doc = DocX.Load(filename);

                Formatting normalRegular = new Formatting();
                Formatting boldRegular = new Formatting();
                boldRegular.Bold = true;

                if (!String.IsNullOrEmpty(nomorsurat) && nomorsurat.ToLower() == "undefined") nomorsurat = "";
                if (!String.IsNullOrEmpty(NamaProsedur) && NamaProsedur.ToLower() == "undefined") NamaProsedur = "";
                if (!String.IsNullOrEmpty(namapemohon) && namapemohon.ToLower() == "undefined") namapemohon = "";
                if (!String.IsNullOrEmpty(SetoranPnbp) && SetoranPnbp.ToLower() == "undefined") SetoranPnbp = "";
                if (!String.IsNullOrEmpty(JumlahBayar) && JumlahBayar.ToLower() == "undefined") JumlahBayar = "";

                string pegawaiId = new Pnbp.Codes.Functions().claimUser().PegawaiId;
                string kantorId = new Pnbp.Codes.Functions().claimUser().KantorId;
                Pegawai pegawai = pengembalianmodel.GetKepalaKantor(kantorId);
                string tipe = OtorisasiUser.GetJenisKantorUser();

                string kotaKantor = pengembalianmodel.GetKotaKantorById(kantorId);
                string namaLayanan = "";
                string nip = pegawaiId;

                if (pegawai == null)
                {
                    doc.ReplaceText("{3}", "........................................... (3)");
                    doc.ReplaceText("{4}", "........................................... (4)");
                    doc.ReplaceText("{5}", "........................................... (5)");
                    doc.ReplaceText("{13}", "Direktur/Kepala Kantor Wilayah/\nKepala Kantor……. (13)");
                    doc.ReplaceText("{14}", "……………………….. (14)");
                    doc.ReplaceText("{15}", "………………….. (15)");
                }
                else
                {
                    ReplaceDocText(doc, "{3}", "........................................... (3)", pegawai.Nama, normalRegular);
                    ReplaceDocText(doc, "{4}", "........................................... (4)", pegawai.Nip, normalRegular);
                    ReplaceDocText(doc, "{5}", "........................................... (5)", pegawai.Jabatan, normalRegular);
                    ReplaceDocText(doc, "{13}", "Direktur/Kepala Kantor Wilayah/\nKepala Kantor……. (13)", pegawai.Jabatan, normalRegular);
                    ReplaceDocText(doc, "{14}", "……………………….. (14)", pegawai.Nama, normalRegular);
                    ReplaceDocText(doc, "{15}", "………………….. (15)", pegawai.Nip, normalRegular);
                }

                if (String.IsNullOrEmpty(kotaKantor))
                {
                    kotaKantor = "..........(11)";
                }

                if ((!String.IsNullOrEmpty(nomorberkas) && nomorberkas.ToLower() == "undefined") || String.IsNullOrEmpty(nomorberkas))
                {
                    nomorberkas = "..........(6)";
                    doc.ReplaceText("{6}", nomorberkas);
                }
                else
                {
                    doc.ReplaceText("{6}", nomorberkas, false, RegexOptions.None, boldRegular);

                    // get nama layanan berkas
                    if (tipe == "Kantah")
                    {
                        namaLayanan = pengembalianmodel.GetNamaLayananBerkasByNo(nomorberkas, kantorId);

                    }
                    else if (tipe == "Kanwil")
                    {
                        namaLayanan = pengembalianmodel.GetNamaLayananBerkasByNoKanwil(nomorberkas, kantorId);
                    }
                }
                if ((!String.IsNullOrEmpty(atasNama) && atasNama.ToLower() == "undefined") || String.IsNullOrEmpty(atasNama))
                {
                    doc.ReplaceText("{7}", "..........(7)");
                }
                else
                {
                    doc.ReplaceText("{7}", atasNama, false, RegexOptions.None, boldRegular);
                }
                if (String.IsNullOrEmpty(namaLayanan))
                {
                    doc.ReplaceText("{8}", "..........(8)");
                }
                else
                {
                    doc.ReplaceText("{8}", namaLayanan, false, RegexOptions.None, boldRegular);
                }
                if ((!String.IsNullOrEmpty(SetoranPnbp) && SetoranPnbp.ToLower() == "undefined") || String.IsNullOrEmpty(SetoranPnbp))
                {
                    doc.ReplaceText("{9}", "..........(9)");
                    doc.ReplaceText("{10}", "..........(10)");
                }
                else
                {
                    long SetoranPnbpAngka = long.Parse(SetoranPnbp.Replace(".", String.Empty));
                    if (SetoranPnbpAngka == 0)
                    {

                        doc.ReplaceText("{9}", "..........(9)");
                        doc.ReplaceText("{10}", "..........(10)");
                    }
                    else
                    {
                        doc.ReplaceText("{9}", "Rp. " + SetoranPnbp, false, RegexOptions.None, boldRegular);
                        doc.ReplaceText("{10}", Terbilang(SetoranPnbpAngka) + " rupiah", false, RegexOptions.None, boldRegular);
                    }
                }
                doc.ReplaceText("{11}", kotaKantor);
                doc.ReplaceText("{12}", DateTime.Now.ToString("dd MMMM yyyy"));

                doc.SaveAs(ms);

                Response.ContentType = "application/msword";
                Response.AddHeader("content-disposition", "inline; filename=" + "Surat Keterangan Pengeluaran.docx");
                Response.AddHeader("content-length", ms.Length.ToString());
                Response.BinaryWrite(ms.ToArray());
                Response.End();
            }
            return View();
        }

        private string Terbilang(long x)
        {
            string[] bilangan = { "", "satu", "dua", "tiga", "empat", "lima", "enam", "tujuh", "delapan", "sembilan", "sepuluh", "sebelas" };
            string temp = "";

            if (x < 12)
            {
                temp = " " + bilangan[x];
            }
            else if (x < 20)

Controllers/SatuanKerjaController.cs
using ClosedXML.Excel;
using System.Diagnostics;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Mime;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using Xceed.Words.NET;
using Pnbp.Entities;
using Pnbp.Models;

namespace Pnbp.Controllers
{
    public class SatuanKerjaController : Controller
    {

        public ActionResult ListSatker()
        {
            SatuanKerjaModel mdl = new SatuanKerjaModel();
            List<SatuanKerja> data = mdl.ListSatuanKerja();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

    }
}

Views/Pengembalian/mon_pengembalian.cshtml
@model Pnbp.Entities.FindPengembalianPnbp
@{
	string jenisKantorUser = @OtorisasiUser.GetJenisKantorUser();
}

<script src='@Url.Content("~/resources/js/infiniteScroll.js")'></script>
<style nonce="MjI3NzUzMQ">
	.panel-container {
		padding: 16px;
	}

	.dataTables_processing[style="display: block;"] {
		display: flex !important;
		justify-content: center;
		align-items: center;
		min-height: 37px;
	}

	.d-flex {
		display: flex;
	}

	.justify-content-center {
		justify-content: center;
	}

	.btn-edit {
		background: #17a2b8;
		border-color: #187787 !important;
	}

		.btn-edit:hover, .btn-edit:focus, .btn-edit:active {
			background: #1594a8 !important;
			border-color: #187787 !important;
		}

	.column-aksi button {
		min-width: 80px;
	}

</style>


<div class="" id="dynamic_content">

	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel panel-container">
				<div class="x_title">
					<h2>Pengembalian PNBP</h2>
					<ul class="nav navbar-right panel_toolbox hide">
						<li>
							<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
						</li>
						<li>
							<a class="close-link"><i class="fa fa-close"></i></a>
						</li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content" id="js-section-pencarian">
                    <form class="form-horizontal form-label-left" role="form" method="post" enctype="multipart/form-data">
                        @Html.AntiForgeryToken()
                        @if (jenisKantorUser == "Pusat")
                        {
                            <input type="hidden" name="jeniskantor" id="jeniskantor" value="Pusat" />
                        }
                        else
                        {
                            <input type="hidden" name="jeniskantor" id="jeniskantor" value="Kantah" />
                        }

                        <div class="row">
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Nomor Berkas : </label>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    @Html.TextBoxFor(m => m.CariNomorBerkas, new { @class = "form-control input-md" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Nama Pemohon : </label>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    @Html.TextBoxFor(m => m.CariNamaPemohon, new { @class = "form-control input-md" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Status : </label>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    @{
                                        var lsStatus = new List<SelectListItem>();
                                        if (jenisKantorUser == "Pusat")
                                        {
                                            lsStatus.Add(new SelectListItem { Value = "1", Text = "Usulan Baru" });
                                        }
                                        else
                                        {
                                            lsStatus.Add(new SelectListItem { Value = "0", Text = "Belum Kirim" });
                                            lsStatus.Add(new SelectListItem { Value = "1", Text = "Terkirim" });
                                        }
                                        lsStatus.Add(new SelectListItem { Value = "2", Text = "Proses" });
                                        lsStatus.Add(new SelectListItem { Value = "3", Text = "Berkas Tidak Lengkap" });
                                        lsStatus.Add(new SelectListItem { Value = "4", Text = "Selesai" });
                                    }
                                    @Html.DropDownListFor(model => model.CariStatus, lsStatus, " -- Pilih Status --", new { @class = "select2_single form-control input-md" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Satker : </label>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    @Html.DropDownListFor(model => model.CariKodeSatker, new List<SelectListItem>(), " -- Pilih Satuan Kerja --", new { @class = "select2_single form-control input-md" })
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <button type="submit" class="btn btn-success">Cari</button>
                            </div>
                        </div>
                        <br>

                        <div class="table-responsive">
                            <table class="table --js-dtable table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Kewenangan</th>
                                        @if (jenisKantorUser == "Pusat")
                                        {
                                            <th>Satuan Kerja</th>
                                        }
                                        <th>Nomor Berkas</th>
                                        <th>Nama Pemohon</th>
                                        <th>Nominal</th>
                                        <th>Nomor Surat</th>
                                        <th>Tangal Pengajuan</th>
                                        <th>SP2D</th>
                                        <th>Status</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody id="dataplaceholder"></tbody>
                            </table>
                        </div>

                    </form>
				</div>
			</div>
		</div>
	</div>

</div>


<div id='myModalDocViewer' class='modal'>
	<div class="modal-dialog">
		<div class="modal-content">
			<div id='myModalContent'></div>
		</div>
	</div>
</div>


<a id="back-to-top" href="#" class="btn btn-primary back-to-top" role="button" title="" data-toggle="tooltip" data-placement="left"><span class="glyphicon glyphicon-chevron-up"></span></a>

<script type="text/javascript" nonce="MjI3NzUzMQ">
    $(function () {
        $("div#loading").hide();
    });

    $(document).ready(function () {

		$('.select2_single').select2({ width: 'resolve' });

        $('#myModalDocViewer').on('shown.bs.modal', function () {
            $(this).find('.modal-dialog').css({
                width: '98%',
                height: '98 %',
                'max-height': '98%'
            });
		});

		$('#js-section-pencarian form').on('submit', function (e) {
			e.preventDefault();
			dTable.draw();
		});

        $(window).scroll(function () {
            if ($(this).scrollTop() > 50) {
                $('#back-to-top').fadeIn();
            } else {
                $('#back-to-top').fadeOut();
            }
        });
        // scroll body to 0px on click
        $('#back-to-top').click(function () {
            $('#back-to-top').tooltip('hide');
            $('body,html').animate({
                scrollTop: 0
            }, 800);
            return false;
        });

        //$('#back-to-top').tooltip('show');

		let dTableColumns = [
			{ "data": "RNumber", "className": "centertaligncolumn", "width": "5%" },
			{ "data": "LabelTipePengembalian", "className": "centertaligncolumn", "width": "5%" },
			{ "data": "NamaSatker", "className": "centertaligncolumn", "width": "20%" },
			{ "data": "NomorBerkas", "className": "centertaligncolumn", "width": "5%" },
			{ "data": "NamaPemohon", "className": "centertaligncolumn", "width": "20%" },
			{ "data": "permohonanpengembalian", "className": "rightaligncolumn", render: formatAngka },
			{ "data": "NomorSurat", "className": "centertaligncolumn", "width": "5%" },
			{ "data": "TanggalPengaju", "className": "centertaligncolumn", "width": "5%" },
			{ "data": "NomorSP2D", "className": "centertaligncolumn", "width": "5%" },
			{
				"data": "StatusPengembalian",
				"className": "centertaligncolumn",
				"width": "10%",
				render: function (data) {
					if (data == null) {
						return 'Belum Kirim'
					}
					if (data == '0') {
						return 'Belum Kirim'
					}
					if (data == '1') {
						if ($('#jeniskantor').val() == 'Pusat') {
							return 'Usulan Baru'
						} else {
							return 'Terkirim'
						}
					}
					if (data == '2') {
						return 'Proses'
					}
					if (data == '3') {
						return 'Berkas Tidak Lengkap'
					}
					if (data == '4') {
						return 'Selesai'
					}
				}
			},
			{
				"data": null,
				"className": "centertaligncolumn column-aksi",
				"width": "5%",
				"render": function (data, type, row) {
					let isPusat = ($('#jeniskantor').val() == 'Pusat');
					let html = '';
					let url = '@Url.Action("DetailPengajuan", "Pengembalian")?pengembalianpnbpid=' + data.PengembalianPnbpId;

					switch (data.StatusPengembalian) {
						case 1:
							if (data.LabelTipePengembalian == "Pusat" && isPusat) {
								html += '<a href="' + url + '" class="btn btn-success btn-edit"><i class="fa fa-pencil"></i> Edit</a>';
							} else if ((data.LabelTipePengembalian == "Daerah" && !isPusat)) {
								html += '<a href="' + url + '" class="btn btn-success">Selesai</a>';
							} else {
								html += '<a href="' + url + '" class="btn btn-primary"><i class="fa fa-eye"></i> Lihat</a>';
							}
							break;
						case 3:
						case 0:
							html += '<a href="' + url + '" class="btn btn-success btn-edit"><i class="fa fa-pencil"></i> Edit</a>';
							break;
						case 2:
							if ((data.LabelTipePengembalian == "Pusat" && isPusat) || (data.LabelTipePengembalian == "Daerah" && !isPusat)) {
								html += '<a href="' + url + '" class="btn btn-success">Selesai</a>';
							} else {
								html += '<a href="' + url + '" class="btn btn-primary"><i class="fa fa-eye"></i> Lihat</a>';
							}
							break;
						case 4:
							html += '<a href="' + url + '" class="btn btn-primary"><i class="fa fa-eye"></i> Lihat</a>';
							break;
						default:
							break;
					}

					html = '<div class="text-center d-flex justify-content-center" style="gap:6px">' + html + '</div>';
					return html;
				}
			},
		];

		if ($('#jeniskantor').val() != 'Pusat') {
			dTableColumns.forEach(function (item, index) {
				if (item.data == 'NamaSatker') {
					dTableColumns.splice(index, 1);
				}
				if (item.data == 'permohonanpengembalian') {
					item.width = '20%';
				}
			})
		};

		let dTable = $('#js-section-pencarian .--js-dtable').DataTable({
			"bLengthChange": false,
			"paging": true,
			"pageLength": 10,
			"bFilter": false,
			"ordering": false,
			"info": false,
			"processing": true,
			"serverSide": true,
			"scrollX": false,
			"ajax": {
				url: '@Url.Action("ListPengembalian", "Pengembalian")',
				type: "POST",
				data: function (data, obj) { var ftp = $('#js-section-pencarian form').serializeArray(); data.form = ftp; ftp.push({ name: "start", value: data.start }, { name: "length", value: data.length }); return ftp; }
			},
			"columns": dTableColumns,
		});

		$('tbody', dTable.table().container()).delegate('tr td', 'click', function (e) {
			var data = dTable.row($(this).closest('tr')).data();
			if (e.target.classList.contains('--js-btn-selesai')) {
				selesai(e);
			}
		});

		function selesai(e) {
			showmsg('Informasi', 'Fitur belum tersedia');
		}

		function formatAngka(data) {
			let formattedString = formatangka(data);
			if (formattedString == 'null') {
				formattedString = '';
			}
			return formattedString;
		}

		function listSatker() {
			$.blockUI({ message: '<div style=\"padding:10px\"><b>Sedang proses... </b><p>harap tunggu</p></div>' });
			$.ajax({
				url: '@Url.Action("ListSatker", "SatuanKerja")',
				type: "GET",
				success: function (data, textStatus, jqXHR) {

					let docFrag = document.createDocumentFragment();

					if (data.length > 0) {
						for (let item of data) {
							opt = document.createElement('option');
							opt.value = item.KodeSatker;
							opt.textContent = item.Nama_Satker;
							docFrag.append(opt);
						}
					}

					let selectNode = $('#js-section-pencarian [name="CariKodeSatker"]');
					selectNode.innerHTML = '';
					selectNode.append(docFrag);
					selectNode.select2({ width: 'resolve' });

					$.unblockUI();
				},
				error: function (jqXHR, textStatus, errorThrown) {
					showmsg("Error", "Gagal memuat satuan kerja");
					$.unblockUI();
				},
			});
		}

		listSatker();

    });

</script>